name: Publish MediaKit to NPM
on:
  push:
    paths:
      - packages/mediakit/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies and build 🔧
        run: npm install && npm run build
      - name: Go to MediaKit directory
        run: cd packages/mediakit
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
